title: Geek House Matsue
email: your-email@example.com
description: >
  Rubyの聖地である島根県松江市にあるギークハウス松江のサイトです。
baseurl: ""
url: "https://geek-house-matsue.github.io/"
github_username: geek-house-matsue

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed